name: Testing context variables
on:
  workflow_dispatch
env:
  cloud: google-cloud
  First_Name: lingo

jobs:
 test_context-variables:
   runs-on: ubuntu-latest
   steps:
   - name: "these are defined by github documentation"
     run: | 
       echo "repository name : ${{github.repository}}"
       echo "workflow name : ${{github.workflow}}"
       echo "triggered by : ${{github.triggering_actor }}"
