name: Testing secret vars

on:
  workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true 
jobs: 
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
    - name: "checking the secret output"
      run: | 
        echo "secret value : ${{ secrets.GIT_KEY }}"
        ${{ secrets.GIT_KEY }}
